In [5]:
import tensorflow as tf
inputs = tf.random.normal([1, 2, 3])
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)
print(output)
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
print(whole_seq_output.shape)

print(final_memory_state)

print(final_carry_state)


(1, 4)
tf.Tensor([[ 0.03265109 -0.13498011  0.04214708  0.10107909]], shape=(1, 4), dtype=float32)
(1, 2, 4)
tf.Tensor([[ 0.09205206  0.03978624 -0.00702111 -0.06888393]], shape=(1, 4), dtype=float32)
tf.Tensor([[ 0.17958067  0.09192587 -0.0256143  -0.14782065]], shape=(1, 4), dtype=float32)
